name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for root
        run: npm ci

      - name: Install dependencies for frontend
        run: cd frontend && npm ci

      - name: Run linter
        run: cd frontend && npm run lint
